[build]
  command = "cd web && npm install && npm run build"
  publish = "web/dist"

[build.environment]
  NODE_VERSION = "18.20.8" # Specify exact version for consistency

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate" # Keep for now, adjust for production